# Generated by Django 4.1.5 on 2023-01-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='humidity',
            fields=[
                ('time', models.TimeField(primary_key=True, serialize=False)),
                ('humdity', models.IntegerField()),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='temp',
            fields=[
                ('time', models.TimeField(primary_key=True, serialize=False)),
                ('temp', models.IntegerField()),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
