# Generated by Django 4.1.5 on 2023-01-26 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humidity',
            name='time',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='temp',
            name='time',
            field=models.DateTimeField(auto_now=True, primary_key=True, serialize=False),
        ),
    ]
