# Generated by Django 4.1.5 on 2023-01-28 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_humdity_humidity_humidity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('plant_id', models.IntegerField(primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='humidity',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='temp',
            name='temp',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='humidity',
            name='plant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.plant'),
        ),
        migrations.AddField(
            model_name='temp',
            name='plant_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.plant'),
        ),
    ]
