# Generated by Django 4.1.5 on 2023-01-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_humidity_plant_id_remove_temp_plant_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='co2',
            fields=[
                ('time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('co2', models.FloatField()),
            ],
            options={
                'ordering': ('time',),
            },
        ),
        migrations.CreateModel(
            name='tvoc',
            fields=[
                ('time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('tvoc', models.FloatField()),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
