# Generated by Django 4.1.5 on 2023-01-31 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_co2_tvoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_no', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('plant_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='co2',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.device'),
        ),
        migrations.AddField(
            model_name='humidity',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.device'),
        ),
        migrations.AddField(
            model_name='temp',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.device'),
        ),
        migrations.AddField(
            model_name='tvoc',
            name='device',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.device'),
        ),
    ]
