# Generated by Django 4.1.5 on 2023-02-02 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_device_co2_device_humidity_device_temp_device_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='light',
            fields=[
                ('time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('red', models.FloatField()),
                ('orange', models.FloatField()),
                ('device', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.device')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
