# Generated by Django 4.1.5 on 2023-02-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_light'),
    ]

    operations = [
        migrations.AddField(
            model_name='light',
            name='blue',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='light',
            name='green',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='light',
            name='violet',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='light',
            name='yellow',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='light',
            name='orange',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='light',
            name='red',
            field=models.FloatField(default=0),
        ),
    ]
