# Generated by Django 4.1.5 on 2023-02-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_plants'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
