# Generated by Django 4.1.5 on 2023-02-06 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_device_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='avglight',
            fields=[
                ('time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('intensity', models.FloatField()),
                ('device', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.device')),
            ],
            options={
                'ordering': ('time',),
            },
        ),
    ]
