# Generated by Django 4.1.5 on 2023-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_avglight'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='login',
            field=models.CharField(default='ccl19', max_length=50),
        ),
    ]
