# Generated by Django 4.1.5 on 2023-02-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_device_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='co2tip',
            field=models.CharField(default='ok', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='humtip',
            field=models.CharField(default='ok', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='lighttip',
            field=models.CharField(default='ok', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='temptip',
            field=models.CharField(default='ok', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='tvoctip',
            field=models.CharField(default='ok', max_length=50),
        ),
    ]
