# Generated by Django 4.1.5 on 2023-02-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_device_co2tip_device_humtip_device_lighttip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('score', models.FloatField()),
                ('user', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('plant', models.CharField(max_length=50)),
            ],
        ),
    ]
