# Generated by Django 4.1.5 on 2023-02-09 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='plant',
        ),
    ]
