# Generated by Django 4.1.5 on 2023-02-09 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_user_id_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='login',
            field=models.ForeignKey(default='ccl19', on_delete=django.db.models.deletion.CASCADE, to='blog.user'),
        ),
    ]
