# Generated by Django 4.1.5 on 2023-02-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_airvelocity'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='plant_name',
            field=models.CharField(default='plant', max_length=50),
            preserve_default=False,
        ),
    ]
